name: toy_bloom
description: A Flutter e-commerce application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.1.0
  web: ^0.1.4-beta
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  uuid: ^4.2.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  path_provider: ^2.1.1
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  timeago: ^3.7.0
  pin_code_fields: ^8.0.1
  lottie: ^2.7.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - .env
    - assets/icons/
    - assets/products/
    - assets/logo.png
    - assets/product_placeholder.png
    - assets/images/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash_icon.png
  android: true
  ios: true